### ISSUE TITLE
Suggestion: rename this repository to api-python

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/api-python#1]
but keep the package name as `opentracing`

**Comment by yurishkuro** [comment]
@bensigelman @adriancole @slimsag you ok with renaming to `api-python`?

**Comment by adriancole** [comment]
yep, prefer opentracing-api-python* but fine with api-python

* dealing with users, I've found many git clone into a shared directory and that explaining how to rename to something less likely to clash isn't that great use of time.

**Comment by yurishkuro** [comment]
ha, this is what I have it called locally. I'm fine with `opentracing-api-python`. I think Go version is the only one that's actually sensitive to the exact repo name, since in Go the import with such name would look like
```Go
import "github.com/opentracing/opentracing-api-go/opentracing"
```

**Comment by adriancole** [comment]
yeah that looks like hell. good point.

**Comment by bensigelman** [comment]
I'll rename it api-python... the original name was just a side-effect of the fact that I couldn't push my rename branch to Uber so I hastily cloned the repo without thinking about the naming inconsistency!

**Comment by adriancole** [comment]
+1 api-python

**Comment by yurishkuro** [comment]
I updated the .io site to match

**Comment by bensigelman** [comment]
Excellent!
